### ISSUE TITLE
Mockup Recyclanexus

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-recyclanexus#1]
[REPORTE DE DISEÑO DE MOCKUP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-recyclanexus/files/14725574/REPORTE.DE.DISENO.DE.MOCKUP.pdf)

**Comment by Irvingzr16** [comment]
Portada: **25** puntos
Procedimiento: **25** puntos
Figuras, ilustraciones y fotografías: **25**
Resultados y conclusiones: **20** Faltan descripción de resultados, solamente se cuenta con el enlace.

Porcentaje obtenido: **95**/100

Calificación: **19**/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
